kanta_str = input("Anna suorakulmiolle kanta: ")
korkeus_str = input("Anna suorakulmiolle korkeus: ")
kanta = float(kanta_str)
korkeus = float(korkeus_str)
piiri = (kanta * 2) + (korkeus * 2)
pintaala = (kanta * korkeus)
print("Suorakulmion piiri: " + str(piiri) + " Suorakulmion pintaala: " + str(pintaala))